# Generated by Django 4.0.4 on 2023-06-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Аватар')),
            ],
        ),
    ]
