# Generated by Django 4.0.4 on 2023-06-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
