# Generated by Django 4.0.4 on 2023-06-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_birth_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('destcription', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
            ],
        ),
    ]
