# Generated by Django 4.0.4 on 2023-07-28 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_alter_dog_breed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Кличка')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='Порода')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog', verbose_name='Собака')),
            ],
            options={
                'verbose_name': 'Предок',
                'verbose_name_plural': 'Предки',
            },
        ),
    ]
