# Generated by Django 4.0.4 on 2023-07-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('date_of_create',), 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
