# Generated by Django 4.0.4 on 2023-07-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count_of_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
