# Generated by Django 4.0.4 on 2023-07-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_count_of_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_create',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
