# Generated by Django 4.0.4 on 2023-08-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='признак версии'),
        ),
    ]
