# Generated by Django 4.0.4 on 2023-06-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Изображение')),
                ('category', models.IntegerField(verbose_name='Категория')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('date_of_create', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('date_of_last_change', models.DateField(blank=True, null=True, verbose_name='Дата последнего изменения')),
            ],
        ),
    ]
